name: fruit_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dashed_circular_progress_bar: ^0.0.6
  device_preview: ^1.2.0
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.6.1
  hive: ^2.2.3
  google_sign_in: ^5.4.0
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  page_transition: ^2.1.0
  progress_line: ^0.1.0
  shared_preferences: ^2.3.3
  flutter_facebook_auth: ^7.1.1
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets\fonts\Cairo\static\Cairo-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
  field_prefix: null
flutter_intl:
  enabled: true
